### ISSUE TITLE
Secrets missing from Readme

### ISSUE THREAD

**Issue by BarakStout** [scholzj/demo-opa-kafka-authorization#1]
Followed the blog post and README instructions, can't get the pods to run. Seem to be missing a K8s `secret`? 

`Warning  Failed     5m39s (x8 over 7m7s)    kubelet, docker-desktop  Error: secret "john" not found`
` Warning  Failed     5m59s (x8 over 7m20s)   kubelet, docker-desktop  Error: secret "matt" not found`

**Comment by scholzj** [comment]
The secrets will be created automatically by the Strimzi operators based on the `KafkaUser` resources. So I guess something went wrong there in your Strimzi setup. But without more logs, hard to say what.

**Comment by BarakStout** [comment]
Yeah. I was mixing namespaces. That's what I get for trying things with a half sleep brain. Works like a charm. Thank you for this!
